// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaM1n6ym5yeaqQCVXFZ1h-yzy7A3w3sXk',
    appId: '1:729756246413:web:ebae5bfca3244556775dc5',
    messagingSenderId: '729756246413',
    projectId: 'quick-push-96e6f',
    authDomain: 'quick-push-96e6f.firebaseapp.com',
    storageBucket: 'quick-push-96e6f.appspot.com',
    measurementId: 'G-69Q9HYGM2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOQ9XrnLB2LjZGRAhHKLA7CDGtakiDfe0',
    appId: '1:729756246413:android:f6f8a6d05014f697775dc5',
    messagingSenderId: '729756246413',
    projectId: 'quick-push-96e6f',
    storageBucket: 'quick-push-96e6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFdKBUd1FsbD7PhVdIBDIyu-PxA9g7H98',
    appId: '1:729756246413:ios:00b884a7d8a4e80b775dc5',
    messagingSenderId: '729756246413',
    projectId: 'quick-push-96e6f',
    storageBucket: 'quick-push-96e6f.appspot.com',
    iosBundleId: 'com.example.game',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFdKBUd1FsbD7PhVdIBDIyu-PxA9g7H98',
    appId: '1:729756246413:ios:116417474ef9e381775dc5',
    messagingSenderId: '729756246413',
    projectId: 'quick-push-96e6f',
    storageBucket: 'quick-push-96e6f.appspot.com',
    iosBundleId: 'com.example.game.RunnerTests',
  );
}
